-- Tabla unica donde se guardan los analisis de conversaciones de alumnos.
-- Las columnas reflejan exactamente lo que se inserta en src/app/api/analyze/route.ts
-- (saveToSupabase).

create table public.analisis (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,

  -- Resultado del analisis de Gemini
  conversacion_anonimizada text,
  categoria text,
  estado text,
  resumen text,
  alertas jsonb,
  positivos jsonb,
  sugerencias jsonb,
  intercambios jsonb
);

-- Indice por fecha para el panel admin (ordena descendente por created_at).
create index analisis_created_at_idx on public.analisis (created_at desc);
